const js = require("@eslint/js");

const SCRIPT_GLOBAL_VAR_PATTERN = [
  "^_",
  "^[A-Z][A-Za-z0-9]*$",
  "^use(State|Effect|Memo|Ref|Callback)$",
  "^(canAccess|useTaste|hasTasteLeft|canUseAI|trackAIUse|handleLogout|fetchSleeperUser|fetchUserLeagues|fetchLeagueRosters|fetchLeagueUsers|fetchLeagueInfo|fetchSeasonStats|fetchSeasonProjections)$",
].join("|");

/** @type {import("eslint").Linter.Config[]} */
module.exports = [
  // ── Ignored paths ──────────────────────────────────────────────────────────
  {
    ignores: [
      "node_modules/**",
      ".claude/**",
      "dist-preview/**",
      "reconai-shared/**",
      "reports/**",
      "tests/**",
      "supabase/**",
      "**/*.min.js",
      "draft-war-room/**",
      "team-comps/**",
      "android/**",
      "ios/**",
      // Node.js test/runner scripts — not browser code
      "ai-training-tests.js",
      "reconai-consistency-tests.js",
    ],
  },

  // ── Browser source files ───────────────────────────────────────────────────
  {
    ...js.configs.recommended,
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      parserOptions: {
        // Allow JSX syntax used by React components transpiled via Babel standalone
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // ── Browser built-ins ───────────────────────────────────────────────
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        alert: "readonly",
        confirm: "readonly",
        location: "readonly",
        navigator: "readonly",
        history: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        crypto: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        prompt: "readonly",
        // ── Script-tag libraries ────────────────────────────────────────────
        App: "readonly",
        S: "readonly",
        OD: "readonly",
        wrLog: "readonly",
        React: "readonly",
        ReactDOM: "readonly",
        marked: "readonly",
        Chart: "readonly",
        Babel: "readonly",
        htmx: "readonly",
        supabase: "readonly",
        Capacitor: "readonly",
        // ── React hooks (destructured from React in core.js; global in script scope) ─
        useState: "readonly",
        useEffect: "readonly",
        useMemo: "readonly",
        useRef: "readonly",
        useCallback: "readonly",
        // ── Tier / auth helpers (core.js) ────────────────────────────────────
        getUserTier: "readonly",
        canAccess: "readonly",
        hasTasteLeft: "readonly",
        useTaste: "readonly",
        canUseAI: "readonly",
        trackAIUse: "readonly",
        hasServerAI: "readonly",
        AUTH_KEY: "readonly",
        SESSION_KEY: "readonly",
        handleLogout: "readonly",
        // ── Sleeper API helpers (core.js) ────────────────────────────────────
        fetchSleeperUser: "readonly",
        fetchUserLeagues: "readonly",
        fetchLeagueRosters: "readonly",
        fetchLeagueUsers: "readonly",
        fetchLeagueInfo: "readonly",
        fetchAllPlayers: "readonly",
        fetchSeasonStats: "readonly",
        fetchSeasonProjections: "readonly",
        fetchJSON: "readonly",
        SLEEPER_BASE_URL: "readonly",
        STATS_YEAR: "readonly",
        // ── Dev/debug flags ──────────────────────────────────────────────────
        DEV_MODE: "readonly",
        DEV_DEBUG: "readonly",
        // ── Chart/UI components (charts.js) ──────────────────────────────────
        Sparkline: "readonly",
        BarChart: "readonly",
        RadarChart: "readonly",
        MiniDonut: "readonly",
        CHART_COLORS: "readonly",
        // ── Shared UI components (components.js) ─────────────────────────────
        PlayerInlineCard: "readonly",
        InlineCareerStats: "readonly",
        SkeletonRows: "readonly",
        SkeletonKPI: "readonly",
        TradeFinderTab: "readonly",
        AlexAvatar: "readonly",
        ALEX_AVATARS: "readonly",
        getAlexAvatar: "readonly",
        setAlexAvatar: "readonly",
        GMMessage: "readonly",
        Tip: "readonly",
        UpgradeGate: "readonly",
        ErrorBoundary: "readonly",
        // ── Tab/panel components (loaded via separate script files) ──────────
        DashboardPanel: "readonly",
        DashboardWidgetPicker: "readonly",
        WIDGET_MODULES: "readonly",
        StarBtn: "readonly",
        IntelligenceBriefWidget: "readonly",
        FieldNotesWidget: "readonly",
        AnalyticsPanel: "readonly",
        MyTeamTab: "readonly",
        FreeAgencyTab: "readonly",
        DraftTab: "readonly",
        TradeCalcTab: "readonly",
        LeagueMapTab: "readonly",
        TrophyRoomTab: "readonly",
        CalendarTab: "readonly",
        GlobalDashboard: "readonly",
        SettingsModal: "readonly",
        MockDraftPanel: "readonly",
        // ── Analytics / AI helpers ───────────────────────────────────────────
        runLeagueAnalytics: "readonly",
        getIndustryPickValue: "readonly",
        getKpiAnnotation: "readonly",
        getPlayerAnnotation: "readonly",
        projectPlayerValue: "readonly",
        getAlexStyle: "readonly",
        buildOwnerHistory: "readonly",
        detectRivalries: "readonly",
        dhqContext: "readonly",
        dhqAI: "readonly",
        callClaude: "readonly",
        // ── Sleeper username state (app.js) ───────────────────────────────────
        sleeperUsername: "readonly",
        // ── Board data (draft-room.js) ────────────────────────────────────────
        boardPlayers: "readonly",
        // ── Shared position helpers (reconai/shared/utils.js) ────────────────
        normPos: "readonly",
        getLeaguePositions: "readonly",
        isValidLeaguePosition: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { "args": "none", "caughtErrors": "none", "varsIgnorePattern": SCRIPT_GLOBAL_VAR_PATTERN }],
      // builtinGlobals:false so declaring wrLog in core.js doesn't clash with the global entry above
      "no-redeclare": ["error", { "builtinGlobals": false }],
      "no-dupe-keys": "error",
      "no-unreachable": "error",
      "eqeqeq": ["warn", "always", { "null": "ignore" }],
      "no-constant-condition": "warn",
    },
  },

  // ── eslint.config.js itself (Node/CJS) ────────────────────────────────────
  {
    files: ["eslint.config.js"],
    languageOptions: {
      globals: {
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
      },
    },
  },
];
