// Run with:  node --test js/shared/league-wire-portfolio.test.js
// Ported from C2 tests/league-wire-portfolio.cjs (2026-09-27) + the Dynasty HQ
// lazy league-list loader (userLeagues) used when the host has no list.
'use strict';
const test = require('node:test');
const assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm'), path = require('node:path');
test('C2 all-league Wire: progressive editions, fair coverage, filters, account scope, cache reuse, freshness, failures, cancellation', async () => {
    const leagues = ['a', 'b', 'c'].map(id => ({ id, season: '2026', name: 'League ' + id, settings: { playoff_week_start: 15 }, rosters: [{ roster_id: 1, owner_id: id + '1' }, { roster_id: 2, owner_id: id + '2' }], users: [] }));
    const root = { console, setTimeout, clearTimeout, S: {} }; root.window = root; vm.createContext(root);
    for (const f of ['league-live-scores', 'league-live-table', 'league-wire-journal', 'league-wire-portfolio']) vm.runInContext(fs.readFileSync(path.join(__dirname, `${f}.js`), 'utf8'), root);
    const api = root.WrWirePortfolio;
    const calls = []; const timeline = [];
    const fetcher = async url => { calls.push(url); if (url.includes('/state/')) return { ok: true, json: async () => ({ season: '2026', season_type: 'regular', week: 2 }) }; const id = url.split('/league/')[1]?.split('/')[0]; if (url.endsWith('/' + id)) return { ok: true, json: async () => ({ previous_league_id: null }) }; return { ok: true, json: async () => [{ roster_id: 1, points: id === 'a' ? 120 : id === 'b' ? 100 : 90, matchup_id: 1 }, { roster_id: 2, points: 80, matchup_id: 1 }] }; };
        const state = {};
        await api.load({ leagues, accountId: 'user1', fetcher, onUpdate: e => { state[e.league.id] = e; timeline.push([e.league.id, e.currentReady, e.status]); } });
        assert.equal(Object.keys(state).length, 3);
        assert(Object.values(state).every(e => e.status === 'ready'));
        assert(timeline.findIndex(([id, ready]) => id === 'c' && ready) < timeline.findIndex(([, , status]) => status === 'ready'), 'all current editions arrive before the historical queue completes');
        const headlines = api.headlines(Object.values(state));
        assert.equal(new Set(headlines.slice(0, 3).map(s => s.league.id)).size, 3, 'front page gives each league a turn');
        const recaps = api.headlines(Object.values(state), 'recaps', 'b');
        assert(recaps.length); assert(recaps.every(s => s.league.id === 'b' && s.kind === 'recap'));
        const archived = { ...state.a, stories: state.a.stories.concat({ id: 'old-title', text: 'Old title', documentary: true, eventSeason: 2024, weight: 999 }) };
        assert(!api.headlines([archived]).some(s => s.documentary), 'archive facts cannot compete for current multi-league headlines');
        assert(api.headlines([archived], 'history').some(s => s.id === 'old-title'));
        assert.equal(api.lookback([archived]).id, 'old-title');
        assert.equal(api.lookback([archived], 'b'), null, 'lookbacks respect the league filter');
        assert.equal(api.headlines([{ ...state.a, historical: true }]).length, 0, 'past connected seasons are not current headlines');
        assert(api.headlines([{ ...state.a, historical: true }], 'history').every(s => s.documentary), 'past editions stay available as labeled history');
        const fullEdition = { ...state.a, stories: Array.from({ length: 8 }, (_, i) => ({ id: `news-${i}`, text: `Story ${i}`, category: `Desk ${i}`, rosterIds: [i], kind: i % 2 ? 'recap' : 'preview', preview: i % 2 === 0, weight: 90 - i })).concat({ id: 'archive-only', documentary: true, weight: 999 }) };
        assert.equal(api.headlines([fullEdition]).length, 5, 'front-page selection stays concise');
        assert.equal(api.headlines([fullEdition], 'stories').length, 8, 'Stories exposes every current item, including previews outside the front page');
        assert(api.headlines([fullEdition], 'stories').every(s => !s.documentary));
        assert.equal(api.headlines([fullEdition], 'stories', 'b').length, 0, 'Stories respects league scope');
        const matchups = api.headlines([fullEdition], 'matchups', 'a');
        assert.equal(matchups.length, 4, 'This week includes all scheduled matchup previews');
        assert(matchups.every(s => s.preview === true && s.league.id === 'a'), 'This week excludes completed recaps and archives');
        assert.equal(api.headlines([{ ...fullEdition, stories: [{ id: 'not-a-preview', preview: 'true' }] }], 'matchups').length, 0, 'matchup coverage requires an explicit preview flag');
        const before = calls.length;
        await api.load({ leagues, accountId: 'user1', fetcher, onUpdate() {} });
        assert.equal(calls.length - before, 1, 'warm combined edition only checks the calendar');
        root.WrWireRivalries = { list: league => league.id === 'a' ? [{ owners: ['a1', 'a2'], name: 'Local derby' }] : [] };
        const selected = {};
        await api.load({ leagues, accountId: 'user1', fetcher, onUpdate: e => selected[e.league.id] = e });
        assert(selected.a.stories.some(s => s.followedRivalry && s.text.startsWith('Local derby:')), 'saved selections invalidate a warm edition');
        const rivalryDesk = api.headlines(Object.values(selected), 'rivalries', 'a');
        assert(rivalryDesk.length > 0 && rivalryDesk.every(s => s.category === 'Rivalry watch' || s.category === 'Revenge game'));
        delete root.WrWireRivalries;
        const next = calls.length;
        await api.load({ leagues, accountId: 'user2', fetcher, onUpdate() {} });
        assert(calls.length - next > 1, 'account change does not reuse previous account edition');
        const partial = {};
        await api.load({ leagues, accountId: 'user3', force: true, fetcher: async url => url.includes('/league/b/') ? { ok: false } : fetcher(url), onUpdate: e => partial[e.league.id] = e });
        assert.equal(partial.b.status, 'partial'); assert.equal(partial.a.status, 'ready'); assert.equal(partial.c.status, 'ready');
        assert.equal(partial.b.currentReady, false); assert.equal(partial.b.resultsReady, false); assert.equal(partial.b.scheduleReady, false);
        assert(partial.b.currentError.includes('completed scores') && partial.b.currentError.includes('Current matchups'), 'independent current-source failures are not overwritten');
        assert.equal(partial.b.currentUpdatedAt, null, 'failed current reads cannot report fresh evidence');
        const originalHistory = root.App.LeagueLiveTable.loadHistory, originalArchive = root.WrWireStories.loadArchive;
        let clock = 1000;
        const rows = [{ roster_id: 1, points: 120, matchup_id: 1 }, { roster_id: 2, points: 80, matchup_id: 1 }];
        root.App.LeagueLiveTable.loadHistory = async () => ({ priorWeeks: [{ week: 1, rows }], updatedAt: 500 });
        root.WrWireStories.loadArchive = async ({ onProgress }) => { clock = 9000; onProgress({ seasons: [], complete: false }); clock = 12000; return { seasons: [], complete: false, reason: 'One older season is unavailable.' }; };
        const archiveTimeline = [];
        await api.load({ leagues: [leagues[0]], force: true, fetcher, now: () => clock, onUpdate: e => archiveTimeline.push(e) });
        const archivePartial = archiveTimeline.at(-1);
        assert.equal(archivePartial.status, 'partial'); assert.equal(archivePartial.currentReady, true);
        assert.equal(archivePartial.resultsReady, true); assert.equal(archivePartial.scheduleReady, true);
        assert.equal(archivePartial.currentError, ''); assert.equal(archivePartial.archiveError, 'One older season is unavailable.');
        assert.equal(archivePartial.currentUpdatedAt, 500, 'freshness honors cached completed-score age rather than archive completion');
        assert.equal(archivePartial.at, 12000, 'edition publication time remains available separately');
        assert(archiveTimeline.filter(e => e.currentReady).every(e => e.currentUpdatedAt === 500), 'archive progress never advances the current-evidence timestamp');
        root.WrWireStories.loadArchive = async () => ({ seasons: [], complete: true });
        root.App.LeagueLiveTable.loadHistory = async () => { throw Error('Scores unavailable'); };
        for (const testSeason of ['historical', 'postseason']) {
            const league = testSeason === 'historical' ? { ...leagues[0], season: '2025' } : leagues[0];
            let incomplete;
            await api.load({ leagues: [league], force: true, fetcher: async url => url.includes('/state/') ? { ok: true, json: async () => ({ season: '2026', season_type: testSeason === 'postseason' ? 'post' : 'regular', week: 2 }) } : fetcher(url), onUpdate: e => { incomplete = e; } });
            assert.equal(incomplete.resultsReady, false, `${testSeason} failures have no usable results`);
            assert.equal(incomplete.scheduleReady, false, `${testSeason} cannot claim a schedule it never requested`);
            assert.equal(incomplete.currentReady, false); assert.equal(incomplete.currentUpdatedAt, null);
        }
        root.App.LeagueLiveTable.loadHistory = async () => ({ priorWeeks: [], updatedAt: 500 });
        let openingFailure;
        await api.load({ leagues: [leagues[0]], force: true, fetcher: async url => url.includes('/state/') ? { ok: true, json: async () => ({ season: '2026', season_type: 'regular', week: 1 }) } : { ok: false }, onUpdate: e => { openingFailure = e; } });
        assert.equal(openingFailure.resultsReady, false, 'an empty opening-week results window is not usable score evidence');
        assert.equal(openingFailure.scheduleReady, false); assert.equal(openingFailure.currentReady, false); assert.equal(openingFailure.currentUpdatedAt, null);
        root.App.LeagueLiveTable.loadHistory = async () => ({ priorWeeks: [{ week: 1, rows }], updatedAt: 500 });
        let scheduleFailure;
        await api.load({ leagues: [leagues[0]], force: true, fetcher: async url => url.endsWith('/matchups/2') ? { ok: false } : fetcher(url), now: () => clock, onUpdate: e => { scheduleFailure = e; } });
        assert.equal(scheduleFailure.status, 'partial'); assert.equal(scheduleFailure.currentReady, false);
        assert.equal(scheduleFailure.resultsReady, true); assert.equal(scheduleFailure.scheduleReady, false);
        assert.equal(scheduleFailure.currentUpdatedAt, 500); assert.equal(scheduleFailure.archiveError, '');
        assert(scheduleFailure.currentError.includes('Current matchups') && scheduleFailure.stories.some(s => s.kind === 'recap'), 'good results remain usable when upcoming schedules fail');
        let missingWeek;
        await api.load({ leagues: [leagues[0]], force: true, fetcher: async url => url.includes('/state/') ? { ok: true, json: async () => ({ season: '2026', season_type: 'regular', week: 3 }) } : fetcher(url), onUpdate: e => { missingWeek = e; } });
        assert.equal(missingWeek.completedThrough, 1); assert.equal(missingWeek.resultsReady, false); assert.equal(missingWeek.currentReady, false);
        assert.equal(missingWeek.scheduleReady, true); assert.equal(missingWeek.status, 'partial');
        assert(missingWeek.currentError.includes('completed scores'), 'successful HTTP reads with a missing week cannot mark results ready');
        let invalidSchedule;
        await api.load({ leagues: [leagues[0]], force: true, fetcher: async url => url.endsWith('/matchups/2') ? { ok: true, json: async () => [rows[0], rows[0]] } : fetcher(url), onUpdate: e => { invalidSchedule = e; } });
        assert.equal(invalidSchedule.scheduleReady, false, 'duplicated roster rows are not a verified schedule');
        assert.equal(invalidSchedule.currentReady, false);
        let calendarFailure;
        await api.load({ leagues: [leagues[0]], force: true, fetcher: async () => ({ ok: false }), onUpdate: e => { calendarFailure = e; } });
        assert.equal(calendarFailure.status, 'error'); assert.equal(calendarFailure.currentReady, false);
        assert.equal(calendarFailure.resultsReady, false); assert.equal(calendarFailure.scheduleReady, false); assert.equal(calendarFailure.currentUpdatedAt, null);
        assert(calendarFailure.currentError.includes('calendar'));
        // A selection changed by an update listener must not relabel older stories as the new cache key.
        let selectedName = 'First derby', swapped = false;
        root.WrWireRivalries = { list: () => [{ owners: ['a1', 'a2'], name: selectedName }] };
        await api.load({ leagues: [leagues[0]], accountId: 'rivalry-cache-race', force: true, fetcher, onUpdate: e => { if (e.status === 'ready') { selectedName = 'Renamed derby'; swapped = true; } } });
        assert(swapped);
        let renamed;
        await api.load({ leagues: [leagues[0]], accountId: 'rivalry-cache-race', fetcher, onUpdate: e => { renamed = e; } });
        assert(renamed.stories.some(s => s.text.startsWith('Renamed derby:')), 'cache selection key describes stories actually built, even if rivalries change during publication');
        delete root.WrWireRivalries;
        root.App.LeagueLiveTable.loadHistory = originalHistory; root.WrWireStories.loadArchive = originalArchive;
        let authOwner = 'account:first';
        root.App.AccountStorage = { owner: () => authOwner };
        let authUpdates = 0;
        await api.load({ leagues: [leagues[0]], accountId: 'same-provider', force: true, fetcher, onUpdate: () => { authUpdates++; authOwner = 'account:second'; } });
        assert.equal(authUpdates, 1, 'an app-owner switch stops publication of in-flight private editions');
        await api.load({ leagues: [leagues[0]], accountId: 'same-provider', fetcher, onUpdate() {} });
        const beforeOwnerSwitch = calls.length;
        authOwner = 'account:third';
        await api.load({ leagues: [leagues[0]], accountId: 'same-provider', fetcher, onUpdate() {} });
        assert(calls.length > beforeOwnerSwitch + 1, 'an unchanged provider identity cannot reuse another app owner cache');
        delete root.App.AccountStorage;
        const ended = new AbortController(); ended.abort(); let updates = 0;
        await api.load({ leagues, signal: ended.signal, fetcher, onUpdate: () => updates++ }); assert.equal(updates, 0);
        assert.equal(api.period({ ...leagues[0], season: '2025' }, { season: '2026', week: 2 }).end, 14);
        assert.equal(api.period(leagues[0], { season: '2026', season_type: 'pre', week: 4 }).end, 0);
        const ui = fs.readFileSync(path.join(__dirname, '..', 'components', 'league-wire-portfolio.js'), 'utf8');
        assert(ui.includes('showModal()') && ui.includes('onCancel={onClose}') && ui.includes('opener.current?.isConnected'));
        assert(fs.readFileSync(path.join(__dirname, '..', 'components', 'league-wire.js'), 'utf8').includes('setAllWireOpen(true)'), 'the league Wire opens the all-leagues edition');
        void ('PASS all-league Wire: progressive current editions, fair league coverage, filters, account scope, cache reuse, freshness, source-specific failures, full Stories access and cancellation');
});

test('Dynasty HQ: userLeagues loads the Sleeper list once, skips broken leagues, validates ids', async () => {
    const root = { console, setTimeout, clearTimeout, S: {} }; root.window = root; vm.createContext(root);
    for (const f of ['league-live-scores', 'league-live-table', 'league-wire-journal', 'league-wire-portfolio']) vm.runInContext(fs.readFileSync(path.join(__dirname, `${f}.js`), 'utf8'), root);
    const calls = [];
    const fetcher = async url => { calls.push(url); if (/\/user\//.test(url)) return { ok: true, json: async () => [{ league_id: '11', name: 'A', season: '2026' }, { league_id: '22', name: 'B', season: '2026' }] }; if (/\/22\//.test(url)) return { ok: false }; return { ok: true, json: async () => [] }; };
    const list = await root.WrWirePortfolio.userLeagues('123', '2026', { fetcher });
    assert.deepEqual(JSON.parse(JSON.stringify(list.map(l => l.id))), ['11'], 'a league whose rosters fail is skipped, not faked');
    assert.equal(calls.length, 5);
    await root.WrWirePortfolio.userLeagues('123', '2026', { fetcher });
    assert.equal(calls.length, 5, 'cached for the session window');
    assert.equal((await root.WrWirePortfolio.userLeagues('../x', '2026', { fetcher })).length, 0);
    assert.equal((await root.WrWirePortfolio.userLeagues('', '2026', { fetcher })).length, 0);
});

test('review B1: a pre-draft league in All-my-leagues reads "not started", not failed, and publishes no 0.00 stories', async () => {
    const root = { console, setTimeout, clearTimeout, S: {} }; root.window = root; vm.createContext(root);
    for (const f of ['league-live-scores', 'league-live-table', 'league-wire-journal', 'league-wire-portfolio']) vm.runInContext(fs.readFileSync(path.join(__dirname, `${f}.js`), 'utf8'), root);
    const league = { id: 'pre', season: '2026', name: 'Pre-draft', settings: { playoff_week_start: 15 }, rosters: [1, 2, 3, 4].map(i => ({ roster_id: i, owner_id: 'o' + i })), users: [] };
    const zeros = [1, 2, 3, 4].map(i => ({ roster_id: i, matchup_id: Math.ceil(i / 2), points: 0, starters: [] }));
    const fetcher = async url => {
        if (url.includes('/state/')) return { ok: true, json: async () => ({ season: '2026', season_type: 'regular', week: 3 }) };
        if (/\/league\/pre$/.test(url)) return { ok: true, json: async () => ({ previous_league_id: null }) };
        return { ok: true, json: async () => zeros };
    };
    let last;
    await root.WrWirePortfolio.load({ leagues: [league], accountId: 'x', fetcher, onUpdate: e => { last = e; } });
    assert.equal(last.completedThrough, 0);
    assert.equal(last.currentError, '', 'unplayed weeks are not a load failure');
    assert.equal(last.resultsReady, true);
    assert.equal(last.stories.length, 0, 'no “finish level”, no 0.00 crown, no halved-average previews');
});
